"""
HTML Report Builders

Quality dashboard builder extracted from html_generator.py.
"""

from pathlib import Path
from typing import Any, List


def build_quality_dashboard_content(
    generator: Any,
    score_card_cls: type,
    quality_result: Any = None,
    complexity_result: Any = None,
    smell_report: Any = None,
    typing_report: Any = None,
    datetime_report: Any = None,
    forbidden_report: Any = None,
) -> str:
    """Build the unified quality dashboard HTML content."""
    cards = []
    sections: List[str] = []

    if quality_result:
        violation_count = len(quality_result.files_over_threshold)
        cards.append(score_card_cls(
            title="File Length",
            value=str(violation_count),
            label="files over threshold",
            status="good" if violation_count == 0 else "warning" if violation_count < 5 else "bad",
        ))

    if complexity_result:
        cards.append(score_card_cls(
            title="Complexity",
            value=str(complexity_result.total_violations),
            label="complex functions",
            status="good" if complexity_result.total_violations == 0 else
                   "warning" if complexity_result.total_violations < 10 else "bad",
        ))

    if smell_report:
        cards.append(score_card_cls(
            title="Code Smells",
            value=str(smell_report.total_smells),
            label="detected issues",
            status="good" if smell_report.total_smells == 0 else
                   "warning" if smell_report.total_smells < 20 else "bad",
        ))

    if typing_report:
        cards.append(score_card_cls(
            title="Type Coverage",
            value=f"{typing_report.coverage_percentage:.0f}%",
            label=f"threshold: {typing_report.threshold:.0f}%",
            status="good" if typing_report.is_passing else "bad",
        ))

    if datetime_report:
        cards.append(score_card_cls(
            title="Datetime Issues",
            value=str(datetime_report.total_violations),
            label="deprecated/unsafe",
            status="good" if datetime_report.total_violations == 0 else "bad",
        ))

    if forbidden_report:
        cards.append(score_card_cls(
            title="Forbidden Imports",
            value=str(forbidden_report.total_violations),
            label="wrapper violations",
            status="good" if forbidden_report.total_violations == 0 else "bad",
        ))

    if complexity_result and complexity_result.has_violations:
        rows = []
        for fa in complexity_result.file_analyses:
            for func in fa.functions:
                if func.cyclomatic_complexity > 10 or func.cognitive_complexity > 15:
                    severity = generator._generate_severity_badge(
                        func.cyclomatic_severity if isinstance(func.cyclomatic_severity, str)
                        else func.cyclomatic_severity.value
                    )
                    rows.append([
                        Path(fa.file_path).name,
                        func.name,
                        str(func.line_number),
                        str(func.cyclomatic_complexity),
                        str(func.cognitive_complexity),
                        severity,
                    ])
        if rows:
            sections.append(generator._generate_table(
                ["File", "Function", "Line", "Cyclomatic", "Cognitive", "Severity"],
                rows[:30],
                "Complex Functions",
            ))

    if smell_report and smell_report.has_smells:
        rows = []
        for smell in smell_report.smells[:30]:
            severity = generator._generate_severity_badge(
                smell.severity if isinstance(smell.severity, str) else smell.severity.value
            )
            rows.append([
                Path(smell.file_path).name,
                smell.smell_type,
                str(smell.line_number),
                smell.description[:60] + "..." if len(smell.description) > 60 else smell.description,
                severity,
            ])
        sections.append(generator._generate_table(
            ["File", "Smell", "Line", "Description", "Severity"],
            rows,
            "Code Smells",
        ))

    content = f"""
{generator._generate_header("Quality Dashboard")}
{generator._generate_dashboard(cards)}
{"".join(sections)}
<footer>Generated by Asgard Heimdall</footer>
"""
    return generator._wrap_html(content, f"Quality Dashboard - {generator.title}")
